name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t demo-app .

      - name: Test Docker Container
        run: |
          docker run -d --name demo-container -p 8080:8080 demo-app
          sleep 10
          curl -f http://localhost:8080/hello || exit 1
          docker stop demo-container